"""empty message

Revision ID: 3853b37c47d0
Revises: 05167179deff
Create Date: 2025-01-18 17:19:44.030919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3853b37c47d0'
down_revision = '05167179deff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('rejected', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'rejected')
    # ### end Alembic commands ###
