"""empty message

Revision ID: af0f6c6537bd
Revises: b1a4ba1665c4
Create Date: 2025-01-25 13:38:16.987096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af0f6c6537bd'
down_revision = 'b1a4ba1665c4'
branch_labels = None
depends_on = None

# We want these to be handled by the event logic after insertion.
def remove_server_defaults() -> None:
    op.alter_column('character', 'created_at', server_default=None)
    op.alter_column('character', 'updated_at', server_default=None)
    op.alter_column('conversation', 'created_at', server_default=None)
    op.alter_column('conversation', 'updated_at', server_default=None)
    op.alter_column('conversation_tag', 'created_at', server_default=None)
    op.alter_column('conversation_tag', 'updated_at', server_default=None)
    op.alter_column('message', 'created_at', server_default=None)
    op.alter_column('message', 'updated_at', server_default=None)
    op.alter_column('persona', 'created_at', server_default=None)
    op.alter_column('persona', 'updated_at', server_default=None)
    op.alter_column('presets', 'created_at', server_default=None)
    op.alter_column('presets', 'updated_at', server_default=None)
    op.alter_column('prompt', 'created_at', server_default=None)
    op.alter_column('prompt', 'updated_at', server_default=None)
    op.alter_column('tag', 'created_at', server_default=None)
    op.alter_column('tag', 'updated_at', server_default=None)
    op.alter_column('tag_category', 'created_at', server_default=None)
    op.alter_column('tag_category', 'updated_at', server_default=None)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_tag',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['tag_name'], ['tag.name'], ),
    sa.PrimaryKeyConstraint('character_id', 'tag_name')
    )
    op.add_column('character', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")))
    op.add_column('character', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")))
    op.add_column('character', sa.Column('creator', sa.String(), nullable=True))
    op.add_column('character', sa.Column('creator_notes', sa.String(), nullable=True))
    op.add_column('character', sa.Column('character_version', sa.String(), nullable=True))
    op.add_column('character', sa.Column('system_prompt', sa.Text(), nullable=True))
    op.add_column('character', sa.Column('alternate_greetings', sa.ARRAY(sa.Text()), nullable=True))
    op.add_column('conversation', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")))
    op.add_column('conversation', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")))
    op.add_column('conversation_tag', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")))
    op.add_column('conversation_tag', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")))
    op.add_column('message', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")))
    op.add_column('message', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")))
    op.add_column('persona', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")))
    op.add_column('persona', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")))
    op.add_column('presets', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")))
    op.add_column('presets', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")))
    op.add_column('prompt', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")))
    op.add_column('prompt', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")))
    op.add_column('tag', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")))
    op.add_column('tag', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")))
    op.add_column('tag_category', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")))
    op.add_column('tag_category', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")))
    # ### end Alembic commands ###

    remove_server_defaults()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag_category', 'updated_at')
    op.drop_column('tag_category', 'created_at')
    op.drop_column('tag', 'updated_at')
    op.drop_column('tag', 'created_at')
    op.drop_column('prompt', 'updated_at')
    op.drop_column('prompt', 'created_at')
    op.drop_column('presets', 'updated_at')
    op.drop_column('presets', 'created_at')
    op.drop_column('persona', 'updated_at')
    op.drop_column('persona', 'created_at')
    op.drop_column('message', 'updated_at')
    op.drop_column('message', 'created_at')
    op.drop_column('conversation_tag', 'updated_at')
    op.drop_column('conversation_tag', 'created_at')
    op.drop_column('conversation', 'updated_at')
    op.drop_column('conversation', 'created_at')
    op.drop_column('character', 'alternate_greetings')
    op.drop_column('character', 'system_prompt')
    op.drop_column('character', 'character_version')
    op.drop_column('character', 'creator_notes')
    op.drop_column('character', 'creator')
    op.drop_column('character', 'updated_at')
    op.drop_column('character', 'created_at')
    op.drop_table('character_tag')
    # ### end Alembic commands ###
