"""empty message

Revision ID: b1a4ba1665c4
Revises: fbd7ee4b66e7
Create Date: 2025-01-22 16:25:27.738262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a4ba1665c4'
down_revision = 'fbd7ee4b66e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_category',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.add_column('tag', sa.Column('category_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'tag', 'tag_category', ['category_name'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_column('tag', 'category_name')
    op.drop_table('tag_category')
    # ### end Alembic commands ###
