"""empty message

Revision ID: d6fd509d2552
Revises: fff1ed89a635
Create Date: 2025-01-27 23:46:46.371886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6fd509d2552'
down_revision = 'fff1ed89a635'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'rejected_variant_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('message', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('presets', sa.Column('engine', sa.String(), server_default='kobold', nullable=False))
    op.add_column('presets', sa.Column('api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presets', 'api_key')
    op.drop_column('presets', 'engine')
    op.alter_column('message', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('message', 'rejected_variant_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
