"""empty message

Revision ID: e2511845dd01
Revises: 3853b37c47d0
Create Date: 2025-01-20 03:23:38.425941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2511845dd01'
down_revision = '3853b37c47d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('samplers', sa.JSON(), nullable=False),
    sa.Column('sampler_order', sa.JSON(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('llm_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_presets_id'), 'presets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_presets_id'), table_name='presets')
    op.drop_table('presets')
    # ### end Alembic commands ###
