"""empty message

Revision ID: fbd7ee4b66e7
Revises: e2511845dd01
Create Date: 2025-01-20 17:48:09.074478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd7ee4b66e7'
down_revision = 'e2511845dd01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presets', sa.Column('max_context', sa.Integer(), server_default='16384', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presets', 'max_context')
    # ### end Alembic commands ###
