"""empty message

Revision ID: fff1ed89a635
Revises: af0f6c6537bd
Create Date: 2025-01-27 16:21:29.395773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff1ed89a635'
down_revision = 'af0f6c6537bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('character', 'creator',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('character', 'creator_notes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('character', 'character_version',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('message', sa.Column('content_variant_index', sa.Integer(), nullable=True))
    op.add_column('message', sa.Column('rejected_variant_index', sa.Integer(), nullable=True))
    op.add_column('message', sa.Column('variants', sa.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'variants')
    op.drop_column('message', 'rejected_variant_index')
    op.drop_column('message', 'content_variant_index')
    op.alter_column('character', 'character_version',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('character', 'creator_notes',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('character', 'creator',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
