services:
  chatterboxapi:
    build: ./api
    ports:
      - 3001:3001
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - REDIS_HOSTNAME=chatterboxredis
      - REDIS_PORT=6379
    command: bash -c "export DATABASE_URL=${DATABASE_URL} && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 3001 --reload --log-level info"
    depends_on:
      - chatterboxdb
      - chatterboxredis
    volumes:
      - uploaded-images:/usr/src/app/uploaded_images

  chatterboxdb:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

  chatterboxredis:
    image: redis:alpine
    ports:
      - 6379:6379

  chatterboxfe:
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      - API_URL=${API_URL}
    depends_on:
      - chatterboxapi

volumes:
  postgres-db:
  uploaded-images:
